### ISSUE TITLE
:h learnvim not working as expected

### ISSUE THREAD

**Issue by andysaini** [dahu/LearnVim#11]
Hi! I'm trying to install the help file via the mentioned instructions(download learnvim.txt to .vim/doc/, and run :helptags .vim/doc). But every time I issue the :help learnvim command, it autocompletes to 'learnvim-waz' and opens the help file somewhere in the middle. How can I prevent it? I'm using the latest qvim on arch linux!!

If it helps, I'm also using carlhuda/janus starter package.

**Comment by dahu** [comment]
Thanks. Not sure why vim chose the learnvim-waz tag like that.

**Comment by andysaini** [comment]
cool, thanks!
