### ISSUE TITLE
neovim?

### ISSUE THREAD

**Issue by andysaini** [dahu/LearnVim#15]
Hey Barry, I'm a great fan of this tutorial. Is there a plan for a neovim flavor?

**Comment by dahu** [comment]
iiuc, fmoralesc is trying to bundle his vim-tutor-mode plugin with neovim. I gave him permission to use LearnVim material (with credit) within vim-tutor-mode.
Beyond that, I am not actually using neovim, so I have no immediate plans for a neovim version. Apart from the few new features, neovim should not vary so much from vim as to warrant a separate tutorial, surely...?
https://github.com/fmoralesc/vim-tutor-mode

**Comment by andysaini** [comment]
cool!
